//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/TransportSegments/UDPSegment.msg.
//

#ifndef __UDPSEGMENT_M_H
#define __UDPSEGMENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class UDPSegment;
/**
 * Class generated from <tt>src/TransportSegments/UDPSegment.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet UDPSegment
 * {
 *     uint16_t srcPort;
 *     uint16_t destPort;
 *     uint16_t length;
 *     uint16_t checksum;
 *     //uint8_t payload[65536];
 * }
 * </pre>
 */
class UDPSegment : public ::omnetpp::cPacket
{
  protected:
    uint16_t srcPort = 0;
    uint16_t destPort = 0;
    uint16_t length = 0;
    uint16_t checksum = 0;

  private:
    void copy(const UDPSegment& other);

  protected:
    bool operator==(const UDPSegment&) = delete;

  public:
    UDPSegment(const char *name=nullptr, short kind=0);
    UDPSegment(const UDPSegment& other);
    virtual ~UDPSegment();
    UDPSegment& operator=(const UDPSegment& other);
    virtual UDPSegment *dup() const override {return new UDPSegment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint16_t getSrcPort() const;
    virtual void setSrcPort(uint16_t srcPort);

    virtual uint16_t getDestPort() const;
    virtual void setDestPort(uint16_t destPort);

    virtual uint16_t getLength() const;
    virtual void setLength(uint16_t length);

    virtual uint16_t getChecksum() const;
    virtual void setChecksum(uint16_t checksum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UDPSegment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UDPSegment& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline UDPSegment *fromAnyPtr(any_ptr ptr) { return check_and_cast<UDPSegment*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __UDPSEGMENT_M_H

